= Changelog
:url-repo: https://github.com/spring-io/antora-extensions

This document provides a summary of all notable changes to this project by release.
For a detailed view of what's changed, refer to the {url-repo}/commits[commit history] of this project.

== 1.14.6 (2025-07-09)

_No changes since previous release._

== 1.14.5 (2025-07-08)

_No changes since previous release._

== 1.14.4 (2025-02-19)

_No changes since previous release._

== 1.14.3 (2025-02-19)

_No changes since previous release._

== 1.14.2 (2024-08-18)

_No changes since previous release._

== 1.14.1 (2024-08-18)

_No changes since previous release._

== 1.14.0 (2024-08-17)

_No changes since previous release._

== 1.13.1 (2024-08-09)

_No changes since previous release._

== 1.13.0 (2024-07-30)

_No changes since previous release._

== 1.12.1 (2024-07-29)

_No changes since previous release._

== 1.12.0 (2024-07-09)

_No changes since previous release._

== 1.11.1 (2024-05-21)

_No changes since previous release._

== 1.11.0 (2024-05-14)

_No changes since previous release._

== 1.10.0 (2024-04-17)

_No changes since previous release._

== 1.9.0 (2024-04-17)

_No changes since previous release._

== 1.8.3 (2024-04-17)

_No changes since previous release._

== 1.8.2 (2024-01-18)

_No changes since previous release._

== 1.8.1 (2023-11-09)

_No changes since previous release._

== 1.8.0 (2023-10-13)

_No changes since previous release._

== 1.7.0 (2023-10-10)

_No changes since previous release._

== 1.6.0 (2023-09-20)

_No changes since previous release._

== 1.5.0 (2023-06-28)

_No changes since previous release._

== 1.4.2 (2023-06-23)

_No changes since previous release._

== 1.4.1 (2023-06-23)

_No changes since previous release._

== 1.4.0 (2023-06-12)

_No changes since previous release._

== 1.3.0 (2023-04-25)

_No changes since previous release._

== 1.2.0 (2023-04-14)

_No changes since previous release._

== 1.1.0 (2023-02-27)

_No changes since previous release._

== 1.0.0 (2023-01-30)

_No changes since previous release._

== 1.0.0-alpha.2 (2022-12-19)

=== Fixed

* *partial-build-extension*: Resolve repository origin URL when playbook dir is linked worktree

== 1.0.0-alpha.1 (2022-12-14)

_Initial prerelease._
