name: Release
run-name: ${{ github.workflow }} ${{ github.event.inputs.release-version }}
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Enter version to release (e.g., 1.0.1).
        required: false
permissions:
  # Required for OIDC. See https://docs.npmjs.com/trusted-publishers#step-2-configure-your-cicd-workflow
  id-token: write
  contents: write
jobs:
  perform:
    if: github.event_name == 'workflow_dispatch' && github.repository_owner == 'spring-io'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
    - name: Set up release environment
      run: |
        echo RELEASE_VERSION=${{ github.event.inputs.release-version }} >> $GITHUB_ENV
    - name: Build, tag, and publish npm package
      run: ./npm/release.sh
